/* Auto-generated by Zig build system */
#ifndef CRYPTO_ADJUST_CONFIG_ENABLE_BUILTINS_H
#define CRYPTO_ADJUST_CONFIG_ENABLE_BUILTINS_H

/* Empty configuration file */

#endif /* CRYPTO_ADJUST_CONFIG_ENABLE_BUILTINS_H */
