/* Auto-generated by Zig build system */
#ifndef TF_PSA_CRYPTO_CONFIG_CHECK_BEFORE_H
#define TF_PSA_CRYPTO_CONFIG_CHECK_BEFORE_H

/* Configuration check before - no custom checks needed */

#endif /* TF_PSA_CRYPTO_CONFIG_CHECK_BEFORE_H */
